apiVersion: v2
home: https://ryax.tech
keywords:
  - Ryax
  - Serverless
  - Workflow
  - GPU
  - HPC
  - Slurm
  - Cloud
  - Kubernetes
sources:
  - https://gitlab.com/ryax-tech/ryax/ryax-engine
icon: https://user-images.githubusercontent.com/104617518/167607288-537e67fb-bbd2-460a-b263-2e4c79b69196.png
name: ryax-engine
description: Ryax is a open-source Hybrid workflow orchestrator to optimize your AI workflows and applications on multiple infrastructure.
type: application
version: "26.1"
appVersion: "26.1"
dependencies:
  # Ryax core services
  - name: runner
    # For local dev
    # repository: file://../runner/charts/runner
    # version: 0.0.0-dev
    version: 26.1.x
    repository: "oci://registry.ryax.org/release-charts"
  - name: worker
    # For local dev
    # repository: file://../runner/charts/worker
    # version: 0.0.0-dev
    version: 26.1.x
    repository: "oci://registry.ryax.org/release-charts"
  - name: authorization
    # For local dev
    # repository: file://../authorization/chart
    # version: 0.0.0-dev
    version: 26.1.x
    repository: "oci://registry.ryax.org/release-charts"
  - name: action-builder
    # For local dev
    # repository: file://../runner/charts/actionBuilder
    # version: 0.0.0-dev
    version: 26.1.x
    repository: "oci://registry.ryax.org/release-charts"
  - name: common-resources
    # For local dev
    # repository: file://../common-helm-charts/common-resources
    # version: 0.0.0-dev
    version: 26.1.x
    repository: "oci://registry.ryax.org/release-charts"
  # Ryax UI services
  - name: repository
    # For local dev
    # repository: file://../repository/chart
    # version: 0.0.0-dev
    version: 26.1.x
    repository: "oci://registry.ryax.org/release-charts"
  - name: studio
    # For local dev
    # repository: file://../studio/chart
    # version: 0.0.0-dev
    version: 26.1.x
    repository: "oci://registry.ryax.org/release-charts"
  - name: front
    # For local dev
    # repository: file://../front/chart
    # version: 0.0.0-dev
    version: 26.1.x
    repository: "oci://registry.ryax.org/release-charts"
  - name: webui
    # For local dev
    # repository: file://../webui/chart
    # version: 0.0.0-dev
    version: 26.1.0
    repository: "oci://registry.ryax.org/release-charts"

  # Ryax external services: could be replaced with Cloud tools
  # Docker registry
  - name: registry
    # For local dev
    # version: 0.0.0-dev
    # repository: file://../common-helm-charts/registry
    version: 26.1.x
    repository: "oci://registry.ryax.org/release-charts"
  # Postgres database
  - name: datastore
    # For local dev
    # version: 0.0.0-dev
    # repository: file://../common-helm-charts/datastore
    version: 26.1.x
    repository: "oci://registry.ryax.org/release-charts"
  # S3 compatible storage
  - name: minio
    version: 16.x.x
    repository: 'oci://registry-1.docker.io/bitnamicharts'
  # Reverse proxy
  - name: traefik
    version: 39.x.x
    repository: 'https://helm.traefik.io/traefik'
    condition: traefik.deployment.enabled
  # rabbitmq message broker
  - name: rabbitmq
    version: 15.x.x
    repository: 'oci://registry-1.docker.io/bitnamicharts'
  # Observability
  # Prometheus stack with grafana
  - name: kube-prometheus-stack
    version: 81.x.x
    repository: 'https://prometheus-community.github.io/helm-charts'
    condition: kube-prometheus-stack.enabled
  # Tracing
  - name: tempo
    version: 1.x.x
    repository: 'https://grafana.github.io/helm-charts'
    condition: tempo.enabled
