site_name: Ryax Documentation
site_url: https://docs.ryax.tech
repo_url: https://github.com/ryaxTech/ryax-engine
extra:
  homepage: https://ryax.tech
  # TODO: add a version support
  # version:
  #   provider: mike
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
theme:
  name: material
  logo: assets/logo-ryax-white-110.png
  favicon: _static/ryax-icon.png
  features:
    - navigation.footer
    - content.code.copy
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      accent: deep orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
- search
- autorefs

nav:
- ./index.md
- ./concepts/intro.md
- ./howto/install_ryax_kubernetes.md
- ./tutorials/quick_start_guide.md
- Concepts:
  - ./concepts/concepts.md
  - ./concepts/comparisons.md
  - ./concepts/use_cases.md
- Tutorial:
  - ./reference/action_python3.md
  - ./tutorials/action_csharp.md
  - ./tutorials/action_nodejs.md
  - ./tutorials/http_api_json.md
  - ./tutorials/multi-site-workflow.md
  - ./tutorials/reproducible_action_build.md
  - ./howto/jupyter.md
  - ./howto/text_classification_tutorial.md
  - ./howto/spark_piloted_action.md
  - ./howto/video_detection.md
- Administration:
  - ./howto/install_ryax_kubernetes.md
  - ./howto/install_ryax_kubernetes_airgap.md
  - ./howto/worker-install.md
  - ./howto/create-backups.md
  - ./reference/configuration.md
  - ./reference/intelliscale.md
- References:
  - ./reference/action_python3.md
  - ./reference/basic_actions.md
  - ./reference/architecture.md
  - ./reference/ryax_lock.md
  - ./reference/intelliscale.md
  - ./reference/hpc.md
  - ./reference/configuration.md
  - ./reference/glossary.md

